[project]
name = "supernote-cloud"
version = "0.3.0"
description = "Unofficial Python API client that allows you to access your Supernote files through the Supernote Cloud"
readme = "README.md"
authors = [
    { name = "Julian Prester", email = "hi@julianprester.com" },
]
maintainers = [
    { name = "Ryan Bennett", email = "rnbennett@gmail.com" },
]
license = { text = "Apache-2.0" }
requires-python = ">=3.10"
dependencies = [
    "click>=8.1.8",
    "httpx>=0.28.1",
    "pydantic>=2.10.5",
]

[project.scripts]
supernote-cloud = "supernote_cloud.cli:cli"

[project.urls]
Homepage = "https://github.com/rnbennett/supernote-cloud"
Changelog = "https://github.com/rnbennett/supernote-cloud/releases"
Issues = "https://github.com/rnbennett/supernote-cloud/issues"
CI = "https://github.com/rnbennett/supernote-cloud/actions"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
